[Eco-News, PUT/econews/update] The 400 (Bad request) response code is…
GreenCityProject/GreenCityMVP21_team1_October pull request #35
Opened 2024-10-31 15:04 UTC by Andrii-Danylenko

340/[Eco-News, PUT/econews/update] The 400 (Bad request) response code is now documented in the response codes list.

2024-10-31 18:28 UTC, DenisOgr approved these changes

2024-10-31 21:46 UTC, maks741 requested changes

2024-10-31 21:46 UTC, maks741 commented on core/src/main/java/greencity/controller/EcoNewsController.java
> +            @ApiResponse(responseCode = "401", description = HttpStatuses.BAD_REQUEST)
responseCode = "400"

2024-11-03 09:46 UTC, Andrii-Danylenko commented on core/src/main/java/greencity/controller/EcoNewsController.java
> +            @ApiResponse(responseCode = "401", description = HttpStatuses.BAD_REQUEST)
Thanks! Resolved

2024-11-07 10:08 UTC, DwemOV approved these changes

2024-11-07 11:50 UTC, DZotsenko approved these changes

2024-11-14 15:46 UTC, maks741 approved these changes

2024-11-14 15:49 UTC, merged