Andrii danylenko patch 1
GreenCityProject/GreenCityMVP21_team1_October pull request #53
Opened 2024-11-05 13:43 UTC by Andrii-Danylenko

Must have fixed docker compose errors

2024-11-05 14:37 UTC, StannyB9 approved these changes

2024-11-05 18:41 UTC, DenisOgr requested changes

2024-11-05 18:41 UTC, DenisOgr commented on pom.xml
> +                <executions>
Early, I had issue with validation code using that formatter, and we agreed with mentors to remove this validation step.
But I see, that we need formatter in the docker file.
So, could you add a plugin but don't call it in the validation stage:
```
......
<executions>
        <execution>
            <id>format</id>
            <phase>none</phase>
        </execution>
    </executions>
.....
```

2024-11-06 10:00 UTC, DenisOgr approved these changes

2024-11-06 13:30 UTC, SezamUA approved these changes

2024-11-06 13:34 UTC, merged