Create tests for LanguageController
GreenCityProject/GreenCityMVP21_team1_October pull request #6
Opened 2024-10-25 11:38 UTC by StannyB9

2024-10-25 15:22 UTC, SezamUA reviewed
По тесту все коректно. Але стосовно змін в pom.xml в командному проекті - не дуже гарна ідея.

2024-10-27 18:28 UTC, DenisOgr requested changes
Changes in the pom.xml will be influence for all team members in the project.
These changes should be discussed and injected using separate MR.
Please, remove them or discuss on the next meeting with mentors and team.

2024-10-28 08:22 UTC, StannyB9 commented
I have reverted all changes in the pom.xml file to its original state.

2024-10-28 14:59 UTC, SezamUA approved these changes

2024-10-28 15:21 UTC, maks741 approved these changes

2024-10-29 05:06 UTC, DenisOgr approved these changes

2024-10-29 11:08 UTC, merged