Feature/events/edit event #161
GreenCityProject/GreenCityMVP21_team1_October pull request #65
Opened 2024-11-12 20:15 UTC by DmytroKaplun

2024-11-13 18:29 UTC, SupertrampCode requested changes
For my opinion we need merge and test it with EventValidator before merge with dev branch

2024-11-16 20:26 UTC, SezamUA approved these changes

2024-11-19 19:20 UTC, Andrii-Danylenko approved these changes

2024-11-20 15:22 UTC, SupertrampCode approved these changes

2024-11-20 15:23 UTC, merged